GET http://localhost:4000/api/v1/user
Content-Type: application/json


###
POST http://localhost:4000/api/v1/user
Content-Type: application/json

{
  "username": "admin",
  "email": "admin@mail.com",
  "password": "contrasena"
}

###
POST http://localhost:4000/api/v1/auth